---
output:
  html_document:
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
    theme: flatly
editor_options: 
  chunk_output_type: console
---


# MAT 105 - Syllabus

------

```{r setup, include=FALSE}
library(knitr)
library(datasets)
library(tidyverse)
opts_chunk$set(fig.path = "../images/")
opts_chunk$set(echo = TRUE)
opts_chunk$set(warning = FALSE)
opts_chunk$set(message = FALSE)
opts_chunk$set(fig.width = 6.5)
opts_chunk$set(fig.height = 4)
opts_chunk$set(fig.retina = 3)
options(scipen = 999)
```

# Course Information

***

## Meeting Times

|Course Location|Meeting Days|Time|
|:----|:-----|:----|
|Watson 132|Tuesdays & Thursdays|1:40-2:55pm|


## Instructor Information

+----------------------------+-------------------------------+---------------+
| Instructor Information     | Office Location               | Hours         |
+============================+===============================+===============+
| Dr. Che Smith              | Main Office <br>              | MW: 10-11     |
|                            | Watson 283                    |               |
+----------------------------+-------------------------------+---------------+
| chsmith1@davidson.edu <br> | Data CATS, drop in hours <br> | MWF: 1-4pm    |
| (704) 894-2377             | Hurt Hub, Room 212            | TR: 3:30-5pm  |
+----------------------------+-------------------------------+---------------+



## Course Website

All relevant course information will be posted on the [course page](https://mat105.drchesmith.com), including the weekly schedule, readings, and assignments. 

# Course Description

This course is an introduction to statistics as a science of understanding and analyzing data and a powerful tool to unveil bias, discrimination, and inequity. Students will deepen their understanding of social and economic issues on local and global scales through the analysis of real, compelling datasets using R software.

## Learning Outcomes

Together, we will strive for your individual and collective success in achieving the learning outcomes of this course. At the end of this course, you will be able to:

* Understand each step of the data lifecycle, identify potential sources of statistical and human bias, and determine their implications on the scope of inference.
* “Think with data” by using statistical software to explore, analyze, visualize, and interpret nontrivial datasets with immediate relevance and importance to your life.
* Interpret and communicate results correctly, effectively, and in context without relying on statistical jargon.
* Critically consume diverse sources of published data to identify, explain, and evaluate instances of inequality between groups; critique data-based claims; and evaluate data-based decisions.
* Identify and evaluate misuses, distortions, and misrepresentations of data and statistics.
* Apply your statistical literacy to work toward a more just society.


## Curricular Requirements

This course is an introductory course for the Data Science minor and the Applied Mathematics minor; it also satisfies the *Justice, Equality, and Community* and *Mathematical and Quantitative Thought* requirements.

## Prerequisites

There are no prerequisites for this course. The instructor assumes that students have no previous experience with R, computer programming, or statistics.

# Course Materials

## Textbook

Textbook: OpenIntro Statistics <http://openintro.org/os> - Diez, Barr, Çetinkaya-Rundel
CreateSpace, 3rd Edition, 2015 (ISBN: 978-1943450039)

The textbook is freely available online (http://openintro.org/os). You’re welcome to read on
screen or print it out. If you prefer a paperback version you can buy it at the cost of printing
(around $10) on Amazon (http://openintro.org/os). The bookstore will not carry copies
of this text.

## Software

You will need R and RStudio in order to complete the assignments for this course. R and RStudio are installed on all Davidson campus computers. They are also freely available for download here:

R: https://www.r-project.org 

RStudio: https://www.rstudio.com 

Refer to [this tutorial](../tutorials/tutorial1_Install.html) for detailed instructions on downloading and installing R and RStudio on your personal computer. You also have the option of using the cloud version of R, found at <https://rstudio.cloud>; to use this version, you need to set up a free account using your Davidson email address.

# Access and accommodation

The college welcomes requests for accommodations related to disability and will grant those that are determined to be reasonable and maintain the integrity of a program or curriculum. To make such a request or to begin a conversation about a possible request, please contact the Office of Academic Access and Disability Resources, which is located in the Center for Teaching and Learning in the E.H. Little Library: Beth Bleil, Director, bebleil@davidson.edu , 704-894-2129; or Alysen Beaty, Assistant Director, albeaty@davidson.edu , 704-894-2939. It is best to submit accommodation requests within the drop/add period; however, requests can be made at any time in the semester. Please keep in mind that accommodations are not retroactive.

# Attendance policy

Missing class will adversely affect your grade in many ways. In addition, the college attendance policy will be enforced: missing more than 25% of class meetings makes you eligible for a failing grade. Please look carefully at the syllabus during the first week of class. Should there be a conflict between any class session or assignment due date and a religious holiday or observance, athletic contest, or another academic or personal commitment please let me know well in advance. Religious observance warrants a legitimately excused absence. If you must miss class for any reason, excused or otherwise, you are responsible for getting notes from a classmate and turning in all work on time unless otherwise negotiated with me in advance and in writing.

# Course activities

_**Reading.**_ The textbook is a guide to learning basic statistics and data analysis using R, and you should reproduce all the steps in your own scripts. You should also do (most of) the exercises as you come to them. We may also have occasional readings outside of the textbook, including news articles, blog posts, and short video clips. It is critical to your success that you do complete all readings before you come to class. Otherwise, you will find yourself lost and virtually unable to do the in-class activities or homework assignments.

_**Communication on Slack.**_ We will use a [Slack](http://www.slack.com) channel, <https://mat105-introstats.slack.com>, to communicate outside of our class sessions. Many data-focused teams use Slack and similar tools to facilitate communication and collaboration across project teams. Part of your participation grade depends on your engagement in discussions on Slack. [Join](https://join.slack.com/t/mat105-introstats/shared_invite/enQtODk2MjM5ODY2NjEzLTk1Y2M3YmZiNDkzZjlhZGY0YzY5ODdhZjY4ZTBjOTEyYzUyM2U4Yjg5NWU1YWRiMGI4MjdhYzQ3ZTVhZDMxMjk) our class Slack channel. 

_**In-class activities.**_ This course will contain a mixture of short lectures, interspersed with discussions, short demonstrations and presentations. Each class session will involve a significant amount of hands-on work with R and data. I will expect you to have completed the assigned reading _before_ you come to class, and be prepared to ask (and answer) questions about the reading.

_**Homework.**_ Weekly homework assignments (due most Thursdays, before class) will provide you with regular practice with statistics using R. These assignments will build on the material presented in class, but will require you to apply the basic concepts presented in new ways. Assignments will be posted to the course website on Thursdays after class; they are due at the beginning of class on Thursday of the following week (unless otherwise indicated). You are required to complete all homework assignments individually. You may get help on these assignments from Math and Science Center tutors, from Data CATS consultants, or from me. You may also use any existing advice on the Internet. You may not ask anyone else, at Davidson or elsewhere (including the Internet) to help you solve a problem.

_**Exams.**_ There will be two midterm exams to assess your mastery of the material covered in the course. Both midterm exams will take place during class and will be completed individually. At the end of the semester, you will complete a final exam. 


# Getting help

It is normal and expected that all students will need help outside of class with the material in this course. Because a topic like statistics and a language like R are only learned with practice, an important source of help is additional exercises, in the required textbook or optional online resources provided on the course web page. The following additional resources are also available.

_**Office Hours.**_ I welcome you to visit me during the hours listed at the beginning of this document. It is a good practice to make an appointment with me even if outside of the listed hours of availability. I can also address quick and common questions posted on Slack as a public or direct message tagged to me.

_**Data CATS.**_ Part of my office hours overlap with [Data CATS](https://hurthub.davidson.edu/data-cats) drop-in hours. Data CATS offers free assistance to students working on data-focused assignments and projects. Student consultants are highly qualified to help you debug R code, understand basic statistics, perform analyses, and make data visualizations. Additionally, I am there most afternoons to work with you. Data CATS is located in the Hurt Hub, in Room 212 (labeled Tresata Analytics Factory). 

_**Math and Science Center.**_ The Math & Science Center offers free assistance to students in all areas of math and science, with a focus on the introductory courses. Trained and highly qualified peers hold one-on-one and small-group tutoring sessions on a drop-in basis or by appointment, as well as timely recap sessions ahead of scheduled reviews. Emphasis is placed on thinking critically, understanding concepts, making connections, and communicating effectively, not just getting correct answers. In addition, students can start or join a study group and use the MSC as a group or individual study space. It is located in the Center for Teaching & Learning (CTL) on the first floor of the College Library, See [here](https://www.davidson.edu/offices-and-services/center-teaching-and-learning/student-resources/math-science-and-economics-center) for Spring 2020 hours and more information.

_**Honor Code.**_ Please adhere to the Davidson College Honor Pledge.


# Grading

Course grades will be computed as follows:

| Category | Percentage | 
|:----- |---: | 
| Participation | 10% |
| In Class Labs  | 10% |
| Homework | 30% |
| Midterm Exam #1 | 12.5% |
| Midterm Exam #2 | 12.5% |
| Final Exam | 25% |


# Course Schedule

***

*Note that this schedule is tentative and subject to minor changes. The course site will always have the current schedule, list of assignments and due dates. Major announcements will be made on Slack, mainly to direct your attention to changes listed on the course site.*

+-------+------------------------------------------------------+
|Week   | Topic                                                |
+=======+======================================================+
| 1     | Introduction to Statistics and Data <br> Introduction to R and RStudio |
+-------+------------------------------------------------------+
| 2     | Summarizing and Visualizing Data                     |
+-------+------------------------------------------------------+
| 3     | Introduction to Probability                          |
+-------+------------------------------------------------------+
| 4     | Probability distributions <br> Random variables      |
+-------+------------------------------------------------------+
| 5     | Foundations of statistical inference <br> Confidence intervals |
+-------+------------------------------------------------------+
| 6     | Midterm 1 Review and Exam                            |
+-------+------------------------------------------------------+
| 7     | Hypothesis Testing                                   |
+-------+------------------------------------------------------+
| 8     | *SPRING BREAK - NO CLASS*                            |
+-------+------------------------------------------------------+
| 9     | Inference for categorical data                       |
+-------+------------------------------------------------------+
| 10    | Inference for numerical data                         |
+-------+------------------------------------------------------+
| 11    | Midterm 2 Review and Exam                            |
+-------+------------------------------------------------------+
| 12    | Introduction to linear regression <br> Multiple linear regression |
+-------+------------------------------------------------------+
| 13    | Introduction to logistic regression                  |
+-------+------------------------------------------------------+
| 14    | Tuesday, 4/14: *EASTER BREAK - NO CLASS* <br> Other statistical tests and models |
+-------+------------------------------------------------------+
| 15    | Statistical study design <br> Sample size and power  |
+-------+------------------------------------------------------+
| 16    | Putting it all together                              |
+-------+------------------------------------------------------+
| 17    | Course Wrap Up <br> Final Exam Review <br> Final Exam Period begins |
+-------+------------------------------------------------------+
| 18    | Final Exam Period continues                                              |
+-------+------------------------------------------------------+

